name: Bun Compile
on:
  push:
    branches:
      - main
      
jobs: 
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun build ./update.ts --compile --minify --outfile ollamamodelupdater
  
  release:
    needs: compile
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun build ./update.ts --compile --minify --outfile ollamamodelupdater
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ollamamodelupdater
          asset_name: ollamamodelupdater
          asset_content_type: application/octet-stream
          github_token: ${{ secrets.GITHUB_TOKEN }}
