name: Bun Compile
on:
  push:
    branches:
      - main
      
jobs: 
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: 
          bun build ./update.ts --compile --minify --outfile ollamamodelupdater
  
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ needs.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          files: |
            ollamamodelupdater
          token: ${{ secrets.GITHUB_TOKEN }}
