name: Release
on:
  push:
    tags: "v*.*.*"
      
jobs: 
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Compile executable (Linux)
        run: bun run build
      # ref: https://stackoverflow.com/a/71835483
      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ollamamodelupdater